---
- name: Install required packages
  become: true
  apt:
    name:
    - wget
    - gnupg
    - fonts-dejavu
    - fonts-liberation
    - fonts-crosextra-carlito
    - fonts-crosextra-caladea
    state: present
    update_cache: yes

- name: Download Collabora signing key
  become: true
  get_url:
    url: https://collaboraoffice.com/downloads/gpg/collaboraonline-release-keyring.gpg
    dest: /usr/share/keyrings/collaboraonline-release-keyring.gpg
    mode: "0644"

- name: Configure Collabora repository
  become: true
  copy:
    dest: /etc/apt/sources.list.d/collaboraonline.sources
    content: |
      Types: deb
      URIs: https://www.collaboraoffice.com/repos/CollaboraOnline/24.04/customer-deb-{{ collabora_customer_hash }}
      Suites: ./
      Signed-By: /usr/share/keyrings/collaboraonline-release-keyring.gpg

- name: Update apt cache
  become: true
  apt:
    update_cache: yes

- name: Install Collabora Online
  become: true
  apt:
    name:
    - coolwsd
    - nextcloud-office-brand
    state: present
  notify: restart collabora

- name: Configure coolwsd to listen on port 9980
  become: true
  lineinfile:
    path: /etc/coolwsd/coolwsd.xml
    regexp: "<port>"
    line: "      <port>9980</port>"
    insertafter: "<listen"
  notify: restart collabora

- name: Allow Nextcloud server in WOPI allow list
  become: true
  lineinfile:
    path: /etc/coolwsd/coolwsd.xml
    regexp: "<host allow"
    line: '        <host allow="true">{{ nextcloud_domain }}</host>'
    insertafter: "<storage"
  notify: restart collabora

- name: Ensure Collabora service running
  become: true
  service:
    name: coolwsd
    state: started
    enabled: true
