- name: restart apache
  become: true
  service:
    name: apache2
    state: restarted
- name: restart php-fpm
  become: true
  service:
    name: php{{ php_version }}-fpm
    state: restarted
- name: restart redis
  become: true
  service:
    name: redis-server
    state: restarted
