# =========================
# Nextcloud Apache VirtualHost
# =========================
- name: Create Nextcloud VirtualHost configuration
  ansible.builtin.template:
    src: nextcloud.conf.j2
    dest: /etc/apache2/sites-available/nextcloud.conf
    owner: root
    group: root
    mode: "0644"
  notify: restart apache
- name: Enable Nextcloud site
  ansible.builtin.command: a2ensite nextcloud.conf
  args:
    creates: /etc/apache2/sites-enabled/nextcloud.conf
  notify: restart apache
- name: Disable default Apache site
  ansible.builtin.command: a2dissite 000-default.conf
  args:
    removes: /etc/apache2/sites-enabled/000-default.conf
  notify: restart apache
  ignore_errors: true
